/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App.modules.main_menu.views;

import App.modules.main_menu.model.Config;
import App.modules.main_menu.views.First_menu;
import App.modules.users.Admin.Model.Classes.Singleton;
import App.modules.users.Client.views.interfaz_Client;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Collections;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;

/**
 *
 * @author Jorge
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        /*
        Config.getinstance().getTheme();
        this.setTitle("Menu");
	this.setSize(720,500);//ancho x alto
        this.setLocationRelativeTo(null);
	this.setResizable(false);
	Image image =Toolkit.getDefaultToolkit().getImage("src/App/modules/main_menu/views/img/Menu_image.JPG");
	this.setIconImage(image);  
        Trasparenciabotones();
        
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
		addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
               
                dispose();
                new First_menu().setVisible(true);                                              
            }
        });
        
       */         
                
    }
/*
   
    public void Trasparenciabotones(){
        
        btnrAdministrator.setOpaque(false);
        btnrAdministrator.setContentAreaFilled(false);
        btnrAdministrator.setBorderPainted(false);
        
        
        
    }
    
    */
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnreturn = new javax.swing.JButton();
        btnrAdministrator = new javax.swing.JButton();
        bntclient = new javax.swing.JButton();
        btnuser_reg = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);

        btnreturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/modules/main_menu/views/img/1455586597_arrow_return_up_left.png"))); // NOI18N
        btnreturn.setFocusPainted(false);
        btnreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnActionPerformed(evt);
            }
        });

        btnrAdministrator.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnrAdministrator.setForeground(new java.awt.Color(255, 255, 255));
        btnrAdministrator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/modules/main_menu/views/img/administrator.png"))); // NOI18N
        btnrAdministrator.setText("Administrator");
        btnrAdministrator.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnrAdministrator.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnrAdministrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrAdministratorActionPerformed(evt);
            }
        });

        bntclient.setBackground(new java.awt.Color(255, 255, 255));
        bntclient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bntclient.setForeground(new java.awt.Color(255, 255, 255));
        bntclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/modules/main_menu/views/img/1459292729_bag1.png"))); // NOI18N
        bntclient.setText(" Client");
        bntclient.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bntclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntclientActionPerformed(evt);
            }
        });

        btnuser_reg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnuser_reg.setForeground(new java.awt.Color(255, 255, 255));
        btnuser_reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/modules/main_menu/views/img/1459292287_user_anonymous.png"))); // NOI18N
        btnuser_reg.setText("User_reg");
        btnuser_reg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bntclient)
                            .addComponent(btnuser_reg))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnrAdministrator)
                .addContainerGap(559, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnreturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addComponent(btnrAdministrator)
                .addGap(18, 18, 18)
                .addComponent(bntclient)
                .addGap(18, 18, 18)
                .addComponent(btnuser_reg)
                .addGap(112, 112, 112))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 560));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/modules/main_menu/views/img/Menu_image.JPG"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnrAdministratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrAdministratorActionPerformed
        // TODO add your handling code here:
        
     /*
          this.setVisible(false);
      
      new interfaz_Admin().setVisible(true);
       */ 
    }//GEN-LAST:event_btnrAdministratorActionPerformed

    private void bntclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntclientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntclientActionPerformed

    private void btnreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnActionPerformed
        // TODO add your handling code here:
       /* 
        this.dispose();
        new First_menu().setVisible(true);
       */ 
    }//GEN-LAST:event_btnreturnActionPerformed

   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton bntclient;
    public static javax.swing.JButton btnrAdministrator;
    public static javax.swing.JButton btnreturn;
    public static javax.swing.JButton btnuser_reg;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
