/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App.modules.main_menu.views;

import App.classes.BD_Connection;
import App.classes.Mongo_BD_conection;
import App.modules.main_menu.Controler.Controler_main_menu;
import App.modules.main_menu.model.Config;
import App.modules.main_menu.model.bll.First_menu_config_bll;
import App.modules.main_menu.model.bll.Sign_in_BLL;
import App.modules.main_menu.model.dao.Sign_in_DAO;
import App.modules.users.Admin.Model.Classes.Admin;
import App.modules.users.Admin.Model.Classes.Singleton;
import App.modules.users.Admin.Model.Files.File_utils.utils.json;
import App.modules.users.Client.Model.Classes.Client;
import App.modules.users.Client.Model.Classes.Singleton_cli;
import App.modules.users.Client.Model.bll.Client_BLL;
import App.modules.users.Client.Model.dao.Client_DAO;
import App.modules.users.Client.controler.Controlador_Client;
import App.modules.users.Client.views.Change_Client;
import App.modules.users.User_reg.Controler.Controlador_User_reg;
import App.modules.users.User_reg.Model.Classes.Singleton_user_reg;
import App.modules.users.User_reg.Model.Classes.User_reg;
import App.modules.users.User_reg.Model.Files.File_utils.utils.json_user_reg;
import App.modules.users.User_reg.Model.bll.User_reg_BLL;
import App.modules.users.User_reg.Views.Change_User_reg;
import App.utils.Singleton_App;
import App.utils.themes;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * 
 * @author Jorge
 * @version 1.2.7
 */
public class Sign_in extends javax.swing.JFrame {

    /**
     * Creates new form Sign_in
     */
    public Sign_in() {
        initComponents();

        /*
        json.open_config_json();
        Singleton_user_reg.us = new ArrayList<User_reg>();
        json_user_reg.auto_open_user_reg_json();
        Singleton_App.mongo = new Mongo_BD_conection();
        Singleton_App.nom_bd = Singleton_App.mongo.getNom_bd();
        Singleton_App.nom_table = Singleton_App.mongo.getNom_table();
        Singleton_App.client = Mongo_BD_conection.connect();
        BD_Connection.initialize_BasicDataSourceFactory();
        BD_Connection.logStatistics();

        this.setTitle("SIGN IN");
        this.setLocationRelativeTo(null);
        this.setSize(300, 300);//ancho x alto
        this.setResizable(false);
        //Image image = Toolkit.getDefaultToolkit().getImage("src/App/modules/main_menu/views/img/IMG_0279.JPG");
        //this.setIconImage(image);

        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                JOptionPane.showMessageDialog(null, "Saliendo de la aplicación");
                dispose();
                System.exit(0);

            }
        });
*/
    }

        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Error_label = new javax.swing.JLabel();
        User_txt = new javax.swing.JTextField();
        User_label = new javax.swing.JLabel();
        Pass_label = new javax.swing.JLabel();
        Sign_in_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Pass_txt = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Error_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 229, 20));
        getContentPane().add(User_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 220, -1));

        User_label.setForeground(new java.awt.Color(0, 0, 0));
        User_label.setText("Nombre de usuario:");
        getContentPane().add(User_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        Pass_label.setForeground(new java.awt.Color(0, 0, 0));
        Pass_label.setText("Password:");
        getContentPane().add(Pass_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        Sign_in_btn.setBackground(new java.awt.Color(51, 102, 255));
        Sign_in_btn.setForeground(new java.awt.Color(255, 255, 255));
        Sign_in_btn.setText("Sign in");
        Sign_in_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_in_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Sign_in_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Sign in");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, -1));
        getContentPane().add(Pass_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 220, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sign_in_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_in_btnActionPerformed
        // TODO add your handling code here:
/**
        if (Sign_in_BLL.Select_Admin_dni() == 1) {

            // JOptionPane.showMessageDialog(null, Singleton_App.DB_dni);
            new Controler_main_menu(new First_menu(), 0).Start(0);

        } else if (Sign_in_BLL.Select_Admin_dni_mongo() == 1) {

            Client_BLL.modify_from_client();
            //  new Controlador_Client(new Change_Client(), 2).Start(2);

        } else if (Sign_in_DAO.search_Us_dni_array() == 1) {

            User_reg_BLL.modify_from_user();

        } else {

            Error_label.setOpaque(true);
            Error_label.setForeground(Color.red);
            Error_label.setText("ERROR, USUARIO NO ENCONTRADO!!!");

        }

*/
    }//GEN-LAST:event_Sign_in_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Error_label;
    public static javax.swing.JLabel Pass_label;
    public static javax.swing.JPasswordField Pass_txt;
    public static javax.swing.JButton Sign_in_btn;
    public static javax.swing.JLabel User_label;
    public static javax.swing.JTextField User_txt;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
