/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App.modules.main_menu.views;

import App.classes.BD_Connection;
import App.classes.Mongo_BD_conection;
import App.modules.main_menu.Controler.Controler_main_menu;
import App.modules.main_menu.model.Config;
import App.modules.main_menu.model.bll.First_menu_config_bll;
import App.modules.main_menu.model.bll.Sign_in_BLL;
import App.modules.main_menu.model.dao.Sign_in_DAO;
import App.modules.users.Admin.Model.Classes.Admin;
import App.modules.users.Admin.Model.Classes.Singleton;
import App.modules.users.Admin.Model.Files.File_utils.utils.json;
import App.modules.users.Client.Model.Classes.Client;
import App.modules.users.Client.Model.Classes.Singleton_cli;
import App.modules.users.Client.Model.bll.Client_BLL;
import App.modules.users.Client.Model.dao.Client_DAO;
import App.modules.users.Client.controler.Controlador_Client;
import App.modules.users.Client.views.Change_Client;
import App.modules.users.User_reg.Controler.Controlador_User_reg;
import App.modules.users.User_reg.Model.Classes.Singleton_user_reg;
import App.modules.users.User_reg.Model.Classes.User_reg;
import App.modules.users.User_reg.Model.Files.File_utils.utils.json_user_reg;
import App.modules.users.User_reg.Model.bll.User_reg_BLL;
import App.modules.users.User_reg.Views.Change_User_reg;
import App.utils.Singleton_App;
import App.utils.themes;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * 
 * @author Jorge
 * @version 1.2.7
 */
public class Sign_in extends javax.swing.JFrame {

    /**
     * Creates new form Sign_in
     */
    public Sign_in() {
        initComponents();

        json.open_config_json();
        Singleton_user_reg.us = new ArrayList<User_reg>();
        json_user_reg.auto_open_user_reg_json();
        Singleton_App.mongo = new Mongo_BD_conection();
        Singleton_App.nom_bd = Singleton_App.mongo.getNom_bd();
        Singleton_App.nom_table = Singleton_App.mongo.getNom_table();
        Singleton_App.client = Mongo_BD_conection.connect();
        BD_Connection.initialize_BasicDataSourceFactory();
        BD_Connection.logStatistics();

        this.setTitle("SIGN IN");
        this.setLocationRelativeTo(null);
        this.setSize(400, 400);//ancho x alto
        this.setResizable(false);
        //Image image = Toolkit.getDefaultToolkit().getImage("src/App/modules/main_menu/views/img/IMG_0279.JPG");
        //this.setIconImage(image);

        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                JOptionPane.showMessageDialog(null, "Saliendo de la aplicación");
                dispose();
                System.exit(0);

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Error_label = new javax.swing.JLabel();
        User_txt = new javax.swing.JTextField();
        Pass_text = new javax.swing.JTextField();
        User_label = new javax.swing.JLabel();
        Pass_label = new javax.swing.JLabel();
        Sign_in_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        User_label.setText("Nombre de usuario:");

        Pass_label.setText("Password:");

        Sign_in_btn.setText("Sign in");
        Sign_in_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_in_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Sign_in_btn)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Error_label, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(User_label)
                            .addComponent(Pass_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Pass_text, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(User_txt))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(User_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(User_label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pass_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pass_label))
                .addGap(18, 18, 18)
                .addComponent(Sign_in_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(Error_label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sign_in_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_in_btnActionPerformed
        // TODO add your handling code here:

        if (Sign_in_BLL.Select_Admin_dni() == 1) {

            // JOptionPane.showMessageDialog(null, Singleton_App.DB_dni);
            new Controler_main_menu(new First_menu(), 0).Start(0);

        } else if (Sign_in_BLL.Select_Admin_dni_mongo() == 1) {

            Client_BLL.modify_from_client();
            //  new Controlador_Client(new Change_Client(), 2).Start(2);

        } else if (Sign_in_DAO.search_Us_dni_array() == 1) {

            User_reg_BLL.modify_from_user();

        } else {

            Error_label.setOpaque(true);
            Error_label.setForeground(Color.red);
            Error_label.setText("ERROR, USUARIO NO ENCONTRADO!!!");

        }


    }//GEN-LAST:event_Sign_in_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Error_label;
    public static javax.swing.JLabel Pass_label;
    public static javax.swing.JTextField Pass_text;
    public static javax.swing.JButton Sign_in_btn;
    public static javax.swing.JLabel User_label;
    public static javax.swing.JTextField User_txt;
    // End of variables declaration//GEN-END:variables
}
